### ISSUE TITLE
Server' object has no attribute 'serve_forever

### ISSUE THREAD

**Issue by systemtopeople** [hzlmn/sketch#4]
Hello!
I am running a python example.py application
and get an error AttributeError: 'Server' object has no attribute 'serve_forever'

``
Started` server on 127.0.0.1:8080
``
`Traceback` (most recent call `last):`
  `File` "example.py", line 17, in `<module>`
``   run_app(app, `port=8080)`
``  File "/****/sketch/application.py", line 112, in `run_app`
 `loop.run_until_complete(server.serve_forever())`
 `AttributeError:`` 'Server' object has no attribute `'serve_forever' `

Tell me where could be the error? I downloaded the example itself using git clone

**Comment by hzlmn** [comment]
Hi, which python version do you use?
https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.Server.serve_forever
was added in 3.7

**Comment by systemtopeople** [comment]
Hi I use versions 3.5.2 and 3.6.9 on different servers.

**Comment by hzlmn** [comment]
Use python3.7 then, note this library was built just for demonstration possibilities and supporting older python versions is out of the scope.

**Comment by systemtopeople** [comment]
Thanks!

**Comment by robertsdotpm** [comment]
Hey people, if you want the solution it's simply not to call the function. On older python versions when you call the create_server function it automatically 'serves forever.' So as long as you use ensure_future on that it will be fine (you need to use ensure_future over create_task on older python versions.)

In summary you would do 3 things:

1. check whether create_task exists and if not point it to ensure_future. Simple patch for Python 3.6 which is still in wide-use.
2. call create_task on the create_server coroutine -- make sure to save the task somewhere or the garbage collector may try to close it.
3. check whether serve_forever exists -- if it doesn't then you don't need to call it.

I'm posting this for people who may come here in the future from Google. Happy developing.
